<a href="https://colab.research.google.com/github/623020514-5/multivariate/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('nndb_flat.csv')
data.head(10)

     ID               FoodGroup  ... Selenium_USRDA Zinc_USRDA
0  1001  Dairy and Egg Products  ...       0.018182   0.008182
1  1002  Dairy and Egg Products  ...       0.018182   0.004545
2  1003  Dairy and Egg Products  ...       0.000000   0.000909
3  1004  Dairy and Egg Products  ...       0.263636   0.241818
4  1005  Dairy and Egg Products  ...       0.263636   0.236364
5  1006  Dairy and Egg Products  ...       0.263636   0.216364
6  1007  Dairy and Egg Products  ...       0.263636   0.216364
7  1008  Dairy and Egg Products  ...       0.263636   0.267273
8  1009  Dairy and Egg Products  ...       0.514545   0.311818
9  1010  Dairy and Egg Products  ...       0.263636   0.253636

[10 rows x 45 columns]

In [4]:
newb_data = data.iloc[:,7:] 
newb_data.head()

   Energy_kcal  Protein_g  Fat_g  ...  Phosphorus_USRDA  Selenium_USRDA  Zinc_USRDA
0        717.0       0.85  81.11  ...          0.034286        0.018182    0.008182
1        717.0       0.85  81.11  ...          0.032857        0.018182    0.004545
2        876.0       0.28  99.48  ...          0.004286        0.000000    0.000909
3        353.0      21.40  28.74  ...          0.552857        0.263636    0.241818
4        371.0      23.24  29.68  ...          0.644286        0.263636    0.236364

[5 rows x 38 columns]

In [5]:
import numpy as np

In [7]:
corr = np.corrcoef(newb_data.to_numpy().T)

In [8]:
corr.shape

(38, 38)

In [9]:
corr

array([[1.        , 0.11030203, 0.80679472, ..., 0.19518065, 0.05667274,
        0.11276635],
       [0.11030203, 1.        , 0.05471538, ..., 0.44460761, 0.37836917,
        0.41631538],
       [0.80679472, 0.05471538, 1.        , ..., 0.06608644, 0.03755914,
        0.02826352],
       ...,
       [0.19518065, 0.44460761, 0.06608644, ..., 1.        , 0.22368557,
        0.26657694],
       [0.05667274, 0.37836917, 0.03755914, ..., 0.22368557, 1.        ,
        0.20529859],
       [0.11276635, 0.41631538, 0.02826352, ..., 0.26657694, 0.20529859,
        1.        ]])

In [10]:
data = pd.read_csv('/content/Pizza.csv')
data.head(10)

  brand     id   mois   prot    fat   ash  sodium  carb   cal
0     A  14069  27.82  21.43  44.87  5.11    1.77  0.77  4.93
1     A  14053  28.49  21.26  43.89  5.34    1.79  1.02  4.84
2     A  14025  28.35  19.99  45.78  5.08    1.63  0.80  4.95
3     A  14016  30.55  20.15  43.13  4.79    1.61  1.38  4.74
4     A  14005  30.49  21.28  41.65  4.82    1.64  1.76  4.67
5     A  14075  31.14  20.23  42.31  4.92    1.65  1.40  4.67
6     A  14082  31.21  20.97  41.34  4.71    1.58  1.77  4.63
7     A  14097  28.76  21.41  41.60  5.28    1.75  2.95  4.72
8     A  14117  28.22  20.48  45.10  5.02    1.71  1.18  4.93
9     A  14133  27.72  21.19  45.29  5.16    1.66  0.64  4.95