<a href="https://colab.research.google.com/github/623020514-5/multivariate/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv('nndb_flat.csv')
data.head(10)

     ID               FoodGroup  ... Selenium_USRDA Zinc_USRDA
0  1001  Dairy and Egg Products  ...       0.018182   0.008182
1  1002  Dairy and Egg Products  ...       0.018182   0.004545
2  1003  Dairy and Egg Products  ...       0.000000   0.000909
3  1004  Dairy and Egg Products  ...       0.263636   0.241818
4  1005  Dairy and Egg Products  ...       0.263636   0.236364
5  1006  Dairy and Egg Products  ...       0.263636   0.216364
6  1007  Dairy and Egg Products  ...       0.263636   0.216364
7  1008  Dairy and Egg Products  ...       0.263636   0.267273
8  1009  Dairy and Egg Products  ...       0.514545   0.311818
9  1010  Dairy and Egg Products  ...       0.263636   0.253636

[10 rows x 45 columns]

In [6]:
newb_data = data.iloc[:,7:] 
newb_data.head()

   Energy_kcal  Protein_g  Fat_g  ...  Phosphorus_USRDA  Selenium_USRDA  Zinc_USRDA
0        717.0       0.85  81.11  ...          0.034286        0.018182    0.008182
1        717.0       0.85  81.11  ...          0.032857        0.018182    0.004545
2        876.0       0.28  99.48  ...          0.004286        0.000000    0.000909
3        353.0      21.40  28.74  ...          0.552857        0.263636    0.241818
4        371.0      23.24  29.68  ...          0.644286        0.263636    0.236364

[5 rows x 38 columns]

In [7]:
import numpy as np

In [9]:
corr2 = np.corrcoef(newb_data.to_numpy().T) #ดูค่า correlation

In [10]:
corr2.shape #เพื่อดูขนาด(แถว,หลัก)ของค่า correlation

(38, 38)

In [ ]:
corr

In [ ]:
data = pd.read_csv('/content/Pizza.csv')
data.head(10)